apiVersion: apps/v1
kind: Deployment
metadata:
  name: abc-deployment
spec:
  replicas: 2 
  template:
    metadata:
      labels:
        app: abc_deploy
    spec:
      containers:
      - name: abccontainer
        image: gowthamsundarrajan/project:1
