apiVersion: apps/v1
kind: Deployment
metadata:
  name: abc-deployment
spec:
  selector:
    matchLabels:
      app: abc_deploy
  replicas: 2
  template:
    metadata:
      labels:
        app: abc_deploy
    spec:
      containers:
      - name: abc
        image: gowthamsundarrajan/project:1
        ports:
        - containerPort: 80
