---

apiVersion: v1
kind: Service
metadata:
  name: nodeportservice
spec:
  selector:
    app: abctech
  type: NodePort
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 80
    nodePort: 31110
